"use client";

import "./globals.css";
import Header from "../components/header/Header";
import StairsTransition from "../components/page-transition/StairsTransition";
import PageTransition from "../components/page-transition/PageTransition";
import { ReactNode } from "react";
import { store } from "./store/store";
import { Provider } from "react-redux";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <head>
          <title>Portfolio App</title>
          <meta name="description" content="Generated by Youssef Habib" />
          <link rel="icon" href="/imgs/logo.png" type="image/x-icon"></link>
          <meta name="keywords" content="nextjs, react" />
        </head>
        <body style={{ fontFamily: "JetBrains Mono, monospace" }}>
          <Header />
          <StairsTransition />
          <PageTransition>{children}</PageTransition>
        </body>
      </html>
    </Provider>
  );
}
